### ISSUE TITLE
Lets us input numbers instead of a slider bar

### ISSUE THREAD

**Issue by Luna-Nocturna** [Cytraen/MinimapMarkerMagnitude#1]
As the title pretty much explains already is there an easy way to set a scale? For example when trying the plugin I was seeing what exactly it does and changed the default scale. Now it's impossible to get it back to 100%. Even when lowering the DPI of my mouse to the lowest possible at best I can get it at 99% and then it ticks to 101% or back to 99%.

**Comment by Cytraen** [comment]
ImGui sliders let you ctrl+click to input a number instead of just dragging - also applies to MMM.
